<%@ Page Title="" Language="C#" MasterPageFile="~/ComplianceM.Master" AutoEventWireup="true" CodeBehind="Certificate.aspx.cs" Inherits="ComplianceManager.Certificate" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cntPlaceHolder1" runat="server">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="Content/myCompliance.css" />
    <style>
.heading {
    background-color: #f1f8ff; /* Light blue background matching dashboard theme */
    padding: 4px;
    border-bottom: 2px solid #0066cc; /* Darker blue border */
    margin-bottom: 8px;
    font-weight: bold;
    Font-Size: large;
}
 .error-message {color: #721c24;background-color: #f8d7da;padding: 10px;border: 1px solid #f5c6cb;border-radius: 4px;margin-bottom: 15px;display: block;        }
.details-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
 .details-table td { padding: 5px; vertical-align: top; }
 .details-label { font-weight: bold; font-size: 12px; }
 .details-value { font-size: 12px; }
.control-label {
    display: inline-block;
    width: 80px;
    font-size: 12px;
    font-weight: bold;
}
.add-button {
    background-color: #28a745;
    color: white;
    border: none;
    padding: 4px 12px;
    border-radius: 4px;
    cursor: pointer;
    margin-left: 10px;
}
    .add-button:hover {
        background-color: #3bc55a;
    }
.load-button {
    background-color: #0066cc;
    color: white;
    border: none;
    padding: 4px 12px;
    border-radius: 4px;
    cursor: pointer;
    margin-left: 10px;
}
    .load-button:hover {
        background-color: #007bff;
    }
    </style>
    <div id="inner_page">
        <div id="inner_page_main">
            <div class="heading">
                <asp:Label ID="Label1" runat="server" Text="Compliance Certificate" />
            </div>
            <asp:Label ID="lblErrorMessage" runat="server" CssClass="error-message" Visible="false"  />
            <div style="margin: 20px 0;">
                <asp:Label ID="lblPeriodicity" runat="server" Text="Periodicity" AssociatedControlID="ddlPeriod" CssClass="control-label" />
                <%--<asp:TextBox ID="txtPeriodicity" runat="server" Style="width: 120px;height:22px;"></asp:TextBox>--%>
                <asp:DropDownList ID="ddlPeriod" runat="server" AppendDataBoundItems="true" Height="22px"/>
                            &nbsp;&nbsp;
                <asp:Label ID="lblUserName" runat="server" Text="Generated By" AssociatedControlID="ddlUserName" CssClass="control-label"  style="margin-left: 20px;" />
                <asp:DropDownList ID="ddlUserName" Enabled="false" runat="server" DataTextField="UserName" DataValueField="UserId" Width="180px" Height="22px" AutoPostBack="true" />
                    
                <asp:Button ID="btnSearch" runat="server" Text="Load" OnClick="btnSearch_Click" ValidationGroup="add" CssClass="add-button" />
                <asp:Button ID="btnGenerate" runat="server" Text="Generate Certificate" OnClick="btnGenerate_Click" ValidationGroup="add" CssClass="add-button" />
            </div>
<div id="inner_page_bottom">
    <div class="grid-container">
        <asp:GridView ID="GridView1" CssClass="frequency-grid" runat="server" Width="100%" AutoGenerateColumns="False" GridLines="Both" 
                DataKeyNames="CertificateID" OnPageIndexChanging="OnPageIndexChanging"   BorderColor="#E7E7FF" BorderStyle="None" BackColor="White"
                PageSize="15" AllowPaging="true" EmptyDataText="No Compliances assigned." ShowHeaderWhenEmpty="true" HeaderStyle-HorizontalAlign="Center" >
        <Columns>
            <asp:TemplateField HeaderText="SNo" ItemStyle-Width="20px" ItemStyle-HorizontalAlign="Center">
    <ItemTemplate>
        <asp:Label ID="lblSNo" runat="server" Text='<%# Container.DataItemIndex + 1 %>' />
    </ItemTemplate>
</asp:TemplateField>
            <%--<asp:BoundField DataField="CertificateId" HeaderText="Id" ItemStyle-Width="50" HeaderStyle-HorizontalAlign="Center" />--%>
            <asp:BoundField DataField="CertificateNo" HeaderText="Certificate No" ItemStyle-Width="200" HeaderStyle-HorizontalAlign="Center" />
            <asp:BoundField DataField="Period" HeaderText="Period" ItemStyle-Width="100" />
            <asp:BoundField DataField="FileName" HeaderText="File Name" ItemStyle-Width="400" />
            <asp:BoundField DataField="UserName" HeaderText="User Name" ItemStyle-Width="250" />
            <asp:TemplateField ItemStyle-HorizontalAlign="Center" ControlStyle-Width="150" HeaderText="Generated On">
                 <ItemTemplate>
                     <%# Convert.ToDateTime(Eval("GeneratedOn")).ToString("dd/MM/yyyy") %>
                 </ItemTemplate>
             </asp:TemplateField>
            <asp:TemplateField HeaderText="Action" ItemStyle-Width="80">
                <ItemTemplate>
                    <asp:LinkButton ID="lnkDownload" Text="Download" CommandArgument='<%# Eval("CertificatePath") %>' runat="server"
                            OnClientClick='<%# "window.location.href = \"FileDownloadHandler.ashx?fileName=" + Eval("CertificatePath") + "\"; return false;" %>' />
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
        <RowStyle BackColor="#FFFFFF" /> 
        <AlternatingRowStyle BackColor="#F0F0F0" /> 
        <SelectedRowStyle BackColor="#FFFF00" /> 
        <PagerStyle CssClass="pager-style" />
        <EmptyDataTemplate><div align="center">No Certificates generated.</div></EmptyDataTemplate>
    </asp:GridView>
</div>
    </div>
</div>
    </div>
</asp:Content>